### ISSUE TITLE
touchend vs ghost click event

### ISSUE THREAD

**Issue by czb** [nolimits4web/Framework7#430]
I have a weird problem with Framework7 1.0.3. I have `input radio` list by Framework 7. Content (input elements) and checked change is driven by Knockout.js binding.

Four click events are assigned to every input radio element: `Framework.js line 5952`,  `JQuery 2.1.3 line 4112`, `Framework.js line 9158` and  `JQuery 2.1.3 line 4112`. When I click on pc everything works as expected.

When I click on IOS or Android phone the last JQuery event is never called. The process is as follows:

1. Framework7 Handetouchend is fired
2. Framework7 Click event is fired with `forwardedtouchevent` set to true
3. JQuery click event is fired
3. Framework7 Click event is fired with no `forwardedtouchevent` and therefore `allowclick` remains as false
4. Second JQuery click event is never fired

I guess that the second click event is ghost event but I wonder why it comes sooner than the second JQuery click event. As mentioned, the second JQuery event is produced by Knockout.js `checked` binding.

**Comment by nolimits4web** [comment]
It is really really hard to say for me as these fast clicks are driving me crazy a bit. Anyway, just found one issue that is fixed now, probably related, check it

**Comment by czb** [comment]
When I deactivate fastClick, all the events work fine on IOS - so there must be something wrong in fastClick or Swiper or both :). What exactly is the `needsFastClick TimeOut` supposed to do? You declare a variable, then you fill it with setTimout and then you destroy it.

**Comment by nolimits4web** [comment]
There were issue with this option when attr tapping something, it still was true and doesn't allowed any programmatic clicks

**Comment by nolimits4web** [comment]
Anyway, you can always do stopPropagation or stopImmediatePropagation and handle these links manually

**Comment by czb** [comment]
I have installed https://github.com/ftlabs/fastclick to see what happens. The problem persisted also with that library. I have set all the problematic nodes to `class="needsclick"` and that solved the problem. Maybe you could also introduce the `needsclick` class.

**Comment by nolimits4web** [comment]
There is the same thing here, just add "no-fastclick" class to such element

**Comment by Ultimacho** [comment]
Hi!

Does anybody have a sample of binding a Framework7 checkbox (http://www.idangero.us/framework7/docs/checkboxes-radios.html) via knockout? The problem that I experience is that the state of the control is handled via pure css (psuedo class "checked") and no markup changes can be observed thus knockout is just not capable of controlling the data binding between the view object and the corresponding data field.

Any help will be appreciated...
